#!/bin/sh
#This script should be executed from the run directory which should be ref/P*_T_*
#This script has one argument which should be the test name such as c_sw_12x24.test

for i in test_file*.txt
do
  cmp test_file0000.txt $i
done

grep TEST stdout            > temp${$} ; diff temp${$} ../test/test_output/$1 ; /bin/rm temp${$}
grep TEST test_file0000.txt > temp${$} ; diff temp${$} ../test/test_output/$1 ; /bin/rm temp${$}
